// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: api/shortener_v1/shortener.proto

package shortener_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLRequest) Reset() {
	*x = GetShortURLRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLRequest) ProtoMessage() {}

func (x *GetShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLRequest.ProtoReflect.Descriptor instead.
func (*GetShortURLRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *GetShortURLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLResponse) Reset() {
	*x = GetShortURLResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLResponse) ProtoMessage() {}

func (x *GetShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLResponse.ProtoReflect.Descriptor instead.
func (*GetShortURLResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *GetShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type URLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLRequest) Reset() {
	*x = URLRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLRequest) ProtoMessage() {}

func (x *URLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLRequest.ProtoReflect.Descriptor instead.
func (*URLRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *URLRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetBatchShortURLRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BatchUrlRequests []*URLRequest          `protobuf:"bytes,1,rep,name=batch_url_requests,json=batchUrlRequests,proto3" json:"batch_url_requests,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBatchShortURLRequest) Reset() {
	*x = GetBatchShortURLRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchShortURLRequest) ProtoMessage() {}

func (x *GetBatchShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchShortURLRequest.ProtoReflect.Descriptor instead.
func (*GetBatchShortURLRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetBatchShortURLRequest) GetBatchUrlRequests() []*URLRequest {
	if x != nil {
		return x.BatchUrlRequests
	}
	return nil
}

type URLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLResponse) Reset() {
	*x = URLResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLResponse) ProtoMessage() {}

func (x *URLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLResponse.ProtoReflect.Descriptor instead.
func (*URLResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *URLResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *URLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetBatchShortURLResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BatchUrlResponses []*URLResponse         `protobuf:"bytes,1,rep,name=batch_url_responses,json=batchUrlResponses,proto3" json:"batch_url_responses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetBatchShortURLResponse) Reset() {
	*x = GetBatchShortURLResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchShortURLResponse) ProtoMessage() {}

func (x *GetBatchShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchShortURLResponse.ProtoReflect.Descriptor instead.
func (*GetBatchShortURLResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetBatchShortURLResponse) GetBatchUrlResponses() []*URLResponse {
	if x != nil {
		return x.BatchUrlResponses
	}
	return nil
}

type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{8}
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *URL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUrls      []*URL                 `protobuf:"bytes,1,rep,name=user_urls,json=userUrls,proto3" json:"user_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserURLsResponse) GetUserUrls() []*URL {
	if x != nil {
		return x.UserUrls
	}
	return nil
}

type DelUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlsToDel     []string               `protobuf:"bytes,1,rep,name=urls_to_del,json=urlsToDel,proto3" json:"urls_to_del,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserURLsRequest) Reset() {
	*x = DelUserURLsRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserURLsRequest) ProtoMessage() {}

func (x *DelUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DelUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DelUserURLsRequest) GetUrlsToDel() []string {
	if x != nil {
		return x.UrlsToDel
	}
	return nil
}

type DelUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserURLsResponse) Reset() {
	*x = DelUserURLsResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserURLsResponse) ProtoMessage() {}

func (x *DelUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DelUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{12}
}

type GetServiceStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatsRequest) Reset() {
	*x = GetServiceStatsRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatsRequest) ProtoMessage() {}

func (x *GetServiceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{13}
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountUrls     uint32                 `protobuf:"varint,1,opt,name=count_urls,json=countUrls,proto3" json:"count_urls,omitempty"`
	CountUsers    uint32                 `protobuf:"varint,2,opt,name=count_users,json=countUsers,proto3" json:"count_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *Stats) GetCountUrls() uint32 {
	if x != nil {
		return x.CountUrls
	}
	return 0
}

func (x *Stats) GetCountUsers() uint32 {
	if x != nil {
		return x.CountUsers
	}
	return 0
}

type GetServiceStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatsResponse) Reset() {
	*x = GetServiceStatsResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatsResponse) ProtoMessage() {}

func (x *GetServiceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{15}
}

func (x *GetServiceStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetStorageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageStatusRequest) Reset() {
	*x = GetStorageStatusRequest{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageStatusRequest) ProtoMessage() {}

func (x *GetStorageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStorageStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{16}
}

type GetStorageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageStatusResponse) Reset() {
	*x = GetStorageStatusResponse{}
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageStatusResponse) ProtoMessage() {}

func (x *GetStorageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_v1_shortener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStorageStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_v1_shortener_proto_rawDescGZIP(), []int{17}
}

var File_api_shortener_v1_shortener_proto protoreflect.FileDescriptor

const file_api_shortener_v1_shortener_proto_rawDesc = "" +
	"\n" +
	" api/shortener_v1/shortener.proto\x12\fshortener_v1\"7\n" +
	"\x12GetShortURLRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"2\n" +
	"\x13GetShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"4\n" +
	"\x15GetOriginalURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\";\n" +
	"\x16GetOriginalURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"V\n" +
	"\n" +
	"URLRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"a\n" +
	"\x17GetBatchShortURLRequest\x12F\n" +
	"\x12batch_url_requests\x18\x01 \x03(\v2\x18.shortener_v1.URLRequestR\x10batchUrlRequests\"Q\n" +
	"\vURLResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"e\n" +
	"\x18GetBatchShortURLResponse\x12I\n" +
	"\x13batch_url_responses\x18\x01 \x03(\v2\x19.shortener_v1.URLResponseR\x11batchUrlResponses\"\x14\n" +
	"\x12GetUserURLsRequest\"E\n" +
	"\x03URL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"E\n" +
	"\x13GetUserURLsResponse\x12.\n" +
	"\tuser_urls\x18\x01 \x03(\v2\x11.shortener_v1.URLR\buserUrls\"4\n" +
	"\x12DelUserURLsRequest\x12\x1e\n" +
	"\vurls_to_del\x18\x01 \x03(\tR\turlsToDel\"\x15\n" +
	"\x13DelUserURLsResponse\"\x18\n" +
	"\x16GetServiceStatsRequest\"G\n" +
	"\x05Stats\x12\x1d\n" +
	"\n" +
	"count_urls\x18\x01 \x01(\rR\tcountUrls\x12\x1f\n" +
	"\vcount_users\x18\x02 \x01(\rR\n" +
	"countUsers\"D\n" +
	"\x17GetServiceStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x01(\v2\x13.shortener_v1.StatsR\x05stats\"\x19\n" +
	"\x17GetStorageStatusRequest\"\x1a\n" +
	"\x18GetStorageStatusResponse2\x8d\x05\n" +
	"\fShortener_v1\x12R\n" +
	"\vGetShortURL\x12 .shortener_v1.GetShortURLRequest\x1a!.shortener_v1.GetShortURLResponse\x12[\n" +
	"\x0eGetOriginalURL\x12#.shortener_v1.GetOriginalURLRequest\x1a$.shortener_v1.GetOriginalURLResponse\x12a\n" +
	"\x10GetBatchShortURL\x12%.shortener_v1.GetBatchShortURLRequest\x1a&.shortener_v1.GetBatchShortURLResponse\x12R\n" +
	"\vGetUserURLs\x12 .shortener_v1.GetUserURLsRequest\x1a!.shortener_v1.GetUserURLsResponse\x12R\n" +
	"\vDelUserURLs\x12 .shortener_v1.DelUserURLsRequest\x1a!.shortener_v1.DelUserURLsResponse\x12^\n" +
	"\x0fGetServiceStats\x12$.shortener_v1.GetServiceStatsRequest\x1a%.shortener_v1.GetServiceStatsResponse\x12a\n" +
	"\x10GetStorageStatus\x12%.shortener_v1.GetStorageStatusRequest\x1a&.shortener_v1.GetStorageStatusResponseB>Z<github.com/anatolyi0311/cupurl/pkg/shortener_v1;shortener_v1b\x06proto3"

var (
	file_api_shortener_v1_shortener_proto_rawDescOnce sync.Once
	file_api_shortener_v1_shortener_proto_rawDescData []byte
)

func file_api_shortener_v1_shortener_proto_rawDescGZIP() []byte {
	file_api_shortener_v1_shortener_proto_rawDescOnce.Do(func() {
		file_api_shortener_v1_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shortener_v1_shortener_proto_rawDesc), len(file_api_shortener_v1_shortener_proto_rawDesc)))
	})
	return file_api_shortener_v1_shortener_proto_rawDescData
}

var file_api_shortener_v1_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_shortener_v1_shortener_proto_goTypes = []any{
	(*GetShortURLRequest)(nil),       // 0: shortener_v1.GetShortURLRequest
	(*GetShortURLResponse)(nil),      // 1: shortener_v1.GetShortURLResponse
	(*GetOriginalURLRequest)(nil),    // 2: shortener_v1.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil),   // 3: shortener_v1.GetOriginalURLResponse
	(*URLRequest)(nil),               // 4: shortener_v1.URLRequest
	(*GetBatchShortURLRequest)(nil),  // 5: shortener_v1.GetBatchShortURLRequest
	(*URLResponse)(nil),              // 6: shortener_v1.URLResponse
	(*GetBatchShortURLResponse)(nil), // 7: shortener_v1.GetBatchShortURLResponse
	(*GetUserURLsRequest)(nil),       // 8: shortener_v1.GetUserURLsRequest
	(*URL)(nil),                      // 9: shortener_v1.URL
	(*GetUserURLsResponse)(nil),      // 10: shortener_v1.GetUserURLsResponse
	(*DelUserURLsRequest)(nil),       // 11: shortener_v1.DelUserURLsRequest
	(*DelUserURLsResponse)(nil),      // 12: shortener_v1.DelUserURLsResponse
	(*GetServiceStatsRequest)(nil),   // 13: shortener_v1.GetServiceStatsRequest
	(*Stats)(nil),                    // 14: shortener_v1.Stats
	(*GetServiceStatsResponse)(nil),  // 15: shortener_v1.GetServiceStatsResponse
	(*GetStorageStatusRequest)(nil),  // 16: shortener_v1.GetStorageStatusRequest
	(*GetStorageStatusResponse)(nil), // 17: shortener_v1.GetStorageStatusResponse
}
var file_api_shortener_v1_shortener_proto_depIdxs = []int32{
	4,  // 0: shortener_v1.GetBatchShortURLRequest.batch_url_requests:type_name -> shortener_v1.URLRequest
	6,  // 1: shortener_v1.GetBatchShortURLResponse.batch_url_responses:type_name -> shortener_v1.URLResponse
	9,  // 2: shortener_v1.GetUserURLsResponse.user_urls:type_name -> shortener_v1.URL
	14, // 3: shortener_v1.GetServiceStatsResponse.stats:type_name -> shortener_v1.Stats
	0,  // 4: shortener_v1.Shortener_v1.GetShortURL:input_type -> shortener_v1.GetShortURLRequest
	2,  // 5: shortener_v1.Shortener_v1.GetOriginalURL:input_type -> shortener_v1.GetOriginalURLRequest
	5,  // 6: shortener_v1.Shortener_v1.GetBatchShortURL:input_type -> shortener_v1.GetBatchShortURLRequest
	8,  // 7: shortener_v1.Shortener_v1.GetUserURLs:input_type -> shortener_v1.GetUserURLsRequest
	11, // 8: shortener_v1.Shortener_v1.DelUserURLs:input_type -> shortener_v1.DelUserURLsRequest
	13, // 9: shortener_v1.Shortener_v1.GetServiceStats:input_type -> shortener_v1.GetServiceStatsRequest
	16, // 10: shortener_v1.Shortener_v1.GetStorageStatus:input_type -> shortener_v1.GetStorageStatusRequest
	1,  // 11: shortener_v1.Shortener_v1.GetShortURL:output_type -> shortener_v1.GetShortURLResponse
	3,  // 12: shortener_v1.Shortener_v1.GetOriginalURL:output_type -> shortener_v1.GetOriginalURLResponse
	7,  // 13: shortener_v1.Shortener_v1.GetBatchShortURL:output_type -> shortener_v1.GetBatchShortURLResponse
	10, // 14: shortener_v1.Shortener_v1.GetUserURLs:output_type -> shortener_v1.GetUserURLsResponse
	12, // 15: shortener_v1.Shortener_v1.DelUserURLs:output_type -> shortener_v1.DelUserURLsResponse
	15, // 16: shortener_v1.Shortener_v1.GetServiceStats:output_type -> shortener_v1.GetServiceStatsResponse
	17, // 17: shortener_v1.Shortener_v1.GetStorageStatus:output_type -> shortener_v1.GetStorageStatusResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_shortener_v1_shortener_proto_init() }
func file_api_shortener_v1_shortener_proto_init() {
	if File_api_shortener_v1_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shortener_v1_shortener_proto_rawDesc), len(file_api_shortener_v1_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortener_v1_shortener_proto_goTypes,
		DependencyIndexes: file_api_shortener_v1_shortener_proto_depIdxs,
		MessageInfos:      file_api_shortener_v1_shortener_proto_msgTypes,
	}.Build()
	File_api_shortener_v1_shortener_proto = out.File
	file_api_shortener_v1_shortener_proto_goTypes = nil
	file_api_shortener_v1_shortener_proto_depIdxs = nil
}
